"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { supabase } from "@/lib/supabase/client";

type Employee={id:string;employee_number:string;first_name:string;last_name:string};
type Plan={id:string;code:string;name:string;benefit_type:string;provider:string|null;employee_cost:number;employer_cost:number;tax_treatment:string;is_active:boolean};
type Enrollment={id:string;employee_id:string;benefit_plan_id:string;coverage_level:string|null;employee_cost_override:number|null;employer_cost_override:number|null;effective_from:string;effective_to:string|null;status:string};
const input="h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 focus:border-brand-300 focus:outline-none focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90";
const card="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]";
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function BenefitsManager(){
 const [employees,setEmployees]=useState<Employee[]>([]);const [plans,setPlans]=useState<Plan[]>([]);const [enrollments,setEnrollments]=useState<Enrollment[]>([]);const [employeeId,setEmployeeId]=useState("");const [message,setMessage]=useState<string|null>(null);
 const [code,setCode]=useState("");const [name,setName]=useState("");const [type,setType]=useState("health");const [provider,setProvider]=useState("");const [employeeCost,setEmployeeCost]=useState("0");const [employerCost,setEmployerCost]=useState("0");const [tax,setTax]=useState("pre_tax");
 const [planId,setPlanId]=useState("");const [coverage,setCoverage]=useState("");const [effectiveFrom,setEffectiveFrom]=useState(new Date().toISOString().slice(0,10));
 async function load(){const [e,p,b]=await Promise.all([supabase.from("hr_employees").select("id,employee_number,first_name,last_name").in("employment_status",["active","on_leave"]).order("last_name"),supabase.from("hr_benefit_plans").select("id,code,name,benefit_type,provider,employee_cost,employer_cost,tax_treatment,is_active").order("name"),supabase.from("hr_employee_benefits").select("id,employee_id,benefit_plan_id,coverage_level,employee_cost_override,employer_cost_override,effective_from,effective_to,status").order("effective_from",{ascending:false})]);for(const r of [e,p,b])if(r.error)throw r.error;const es=(e.data??[]) as Employee[];const ps=(p.data??[]) as Plan[];setEmployees(es);setPlans(ps);setEnrollments((b.data??[]) as Enrollment[]);if(!employeeId&&es[0])setEmployeeId(es[0].id);if(!planId&&ps.find(x=>x.is_active))setPlanId(ps.find(x=>x.is_active)!.id);}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Benefits could not be loaded.")); // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 async function createPlan(ev:FormEvent){ev.preventDefault();const {error}=await supabase.from("hr_benefit_plans").insert({code:code.trim().toUpperCase(),name:name.trim(),benefit_type:type,provider:provider.trim()||null,employee_cost:Number(employeeCost),employer_cost:Number(employerCost),tax_treatment:tax});if(error)return setMessage(error.message);setCode("");setName("");setProvider("");setEmployeeCost("0");setEmployerCost("0");setMessage("Benefit plan created.");await load();}
 async function enroll(ev:FormEvent){ev.preventDefault();const {error}=await supabase.from("hr_employee_benefits").insert({employee_id:employeeId,benefit_plan_id:planId,coverage_level:coverage.trim()||null,effective_from:effectiveFrom,status:"active"});if(error)return setMessage(error.message);setCoverage("");setMessage("Employee enrolled.");await load();}
 async function endEnrollment(id:string){const {error}=await supabase.from("hr_employee_benefits").update({status:"ended",effective_to:new Date().toISOString().slice(0,10)}).eq("id",id);if(error)setMessage(error.message);else await load();}
 const employeeMap=useMemo(()=>new Map(employees.map(e=>[e.id,`${e.employee_number} · ${e.first_name} ${e.last_name}`])),[employees]);const planMap=useMemo(()=>new Map(plans.map(p=>[p.id,p])),[plans]);
 return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Benefits</h1><p className="mt-1 text-sm text-gray-500">Health, dental, vision, retirement and other employee benefit plans.</p></div>{message&&<div className={card+" text-sm"}>{message}</div>}
 <div className="grid gap-6 xl:grid-cols-2"><form onSubmit={createPlan} className={card+" space-y-3"}><h2 className="font-semibold text-gray-800 dark:text-white/90">New Benefit Plan</h2><div className="grid grid-cols-2 gap-3"><input className={input} placeholder="Code" value={code} onChange={e=>setCode(e.target.value)} required/><input className={input} placeholder="Plan name" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="grid grid-cols-2 gap-3"><select className={input} value={type} onChange={e=>setType(e.target.value)}>{["health","dental","vision","retirement","life","disability","other"].map(x=><option key={x} value={x}>{x}</option>)}</select><input className={input} placeholder="Provider" value={provider} onChange={e=>setProvider(e.target.value)}/></div><div className="grid grid-cols-3 gap-3"><input className={input} type="number" min="0" step="0.01" placeholder="Employee cost" value={employeeCost} onChange={e=>setEmployeeCost(e.target.value)}/><input className={input} type="number" min="0" step="0.01" placeholder="Employer cost" value={employerCost} onChange={e=>setEmployerCost(e.target.value)}/><select className={input} value={tax} onChange={e=>setTax(e.target.value)}><option value="pre_tax">Pre-tax</option><option value="post_tax">Post-tax</option><option value="non_taxable">Non-taxable</option></select></div><button className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white">Create Plan</button></form>
 <form onSubmit={enroll} className={card+" space-y-3"}><h2 className="font-semibold text-gray-800 dark:text-white/90">Enroll Employee</h2><select className={input} value={employeeId} onChange={e=>setEmployeeId(e.target.value)} required>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_number} · {e.first_name} {e.last_name}</option>)}</select><select className={input} value={planId} onChange={e=>setPlanId(e.target.value)} required>{plans.filter(p=>p.is_active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input className={input} placeholder="Coverage level (employee/family...)" value={coverage} onChange={e=>setCoverage(e.target.value)}/><input className={input} type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)}/></div><button className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white">Enroll</button></form></div>
 <div className={card+" overflow-hidden p-0"}><div className="border-b border-gray-200 px-4 py-3 dark:border-gray-800"><h2 className="font-semibold text-gray-800 dark:text-white/90">Benefit Plans</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-white/[0.02]"><tr><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Provider</th><th className="px-4 py-3 text-right">Employee</th><th className="px-4 py-3 text-right">Employer</th><th className="px-4 py-3">Tax</th></tr></thead><tbody>{plans.map(p=><tr key={p.id} className="border-t border-gray-100 dark:border-gray-800"><td className="px-4 py-3 font-medium">{p.code} · {p.name}</td><td className="px-4 py-3 capitalize">{p.benefit_type}</td><td className="px-4 py-3">{p.provider||"—"}</td><td className="px-4 py-3 text-right">{money.format(Number(p.employee_cost))}</td><td className="px-4 py-3 text-right">{money.format(Number(p.employer_cost))}</td><td className="px-4 py-3">{p.tax_treatment.replace("_","-")}</td></tr>)}</tbody></table></div></div>
 <div className={card+" overflow-hidden p-0"}><div className="border-b border-gray-200 px-4 py-3 dark:border-gray-800"><h2 className="font-semibold text-gray-800 dark:text-white/90">Enrollments</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-white/[0.02]"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Coverage</th><th className="px-4 py-3">Effective</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody>{enrollments.map(b=><tr key={b.id} className="border-t border-gray-100 dark:border-gray-800"><td className="px-4 py-3">{employeeMap.get(b.employee_id)||b.employee_id}</td><td className="px-4 py-3">{planMap.get(b.benefit_plan_id)?.name||b.benefit_plan_id}</td><td className="px-4 py-3">{b.coverage_level||"—"}</td><td className="px-4 py-3">{b.effective_from}{b.effective_to?` → ${b.effective_to}`:""}</td><td className="px-4 py-3 capitalize">{b.status}</td><td className="px-4 py-3 text-right">{b.status==="active"?<button onClick={()=>void endEnrollment(b.id)} className="text-xs text-error-600">End</button>:null}</td></tr>)}</tbody></table></div></div></div>;
}
