"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { supabase } from "@/lib/supabase/client";
import { getCurrentProfile } from "@/lib/supabase/profile";

type Employee = { employee_id:string; employee_number:string; full_name:string; employment_status:string; employment_type:string; department_name:string|null; position_title:string|null };
type Compensation = { id:string; employee_id:string; pay_type:string; base_rate:number; currency_code:string; pay_frequency:string; standard_weekly_hours:number; overtime_eligible:boolean; overtime_multiplier:number; effective_from:string; effective_to:string|null; reason:string|null };
type VariablePay = { id:string; employee_id:string; pay_type:string; amount:number; earning_date:string; status:string; description:string|null };
type Advance = { id:string; employee_id:string; advance_date:string; amount:number; installment_amount:number|null; balance_remaining:number; status:string; reason:string|null };
type Deduction = { id:string; employee_id:string; name:string; deduction_type:string; tax_treatment:string; amount:number|null; percentage:number|null; frequency:string; effective_from:string; effective_to:string|null; is_active:boolean };

const inputClass="h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 focus:border-brand-300 focus:outline-none focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90";
const cardClass="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]";
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function CompensationManager() {
  const [employees,setEmployees]=useState<Employee[]>([]);
  const [employeeId,setEmployeeId]=useState("");
  const [compensation,setCompensation]=useState<Compensation[]>([]);
  const [variablePay,setVariablePay]=useState<VariablePay[]>([]);
  const [advances,setAdvances]=useState<Advance[]>([]);
  const [deductions,setDeductions]=useState<Deduction[]>([]);
  const [canEdit,setCanEdit]=useState(false);
  const [message,setMessage]=useState<string|null>(null);
  const [busy,setBusy]=useState(false);

  const [payType,setPayType]=useState("salary"); const [baseRate,setBaseRate]=useState(""); const [frequency,setFrequency]=useState("biweekly"); const [weeklyHours,setWeeklyHours]=useState("40"); const [overtimeEligible,setOvertimeEligible]=useState(false); const [otMultiplier,setOtMultiplier]=useState("1.5"); const [effectiveFrom,setEffectiveFrom]=useState(new Date().toISOString().slice(0,10)); const [compReason,setCompReason]=useState("");
  const [variableType,setVariableType]=useState("bonus"); const [variableAmount,setVariableAmount]=useState(""); const [earningDate,setEarningDate]=useState(new Date().toISOString().slice(0,10)); const [variableDescription,setVariableDescription]=useState("");
  const [advanceAmount,setAdvanceAmount]=useState(""); const [advanceDate,setAdvanceDate]=useState(new Date().toISOString().slice(0,10)); const [installment,setInstallment]=useState(""); const [advanceReason,setAdvanceReason]=useState("");
  const [deductionName,setDeductionName]=useState(""); const [deductionType,setDeductionType]=useState("fixed"); const [taxTreatment,setTaxTreatment]=useState("post_tax"); const [deductionValue,setDeductionValue]=useState(""); const [deductionFrequency,setDeductionFrequency]=useState("recurring"); const [deductionStart,setDeductionStart]=useState(new Date().toISOString().slice(0,10));

  async function loadEmployees(){
    const [{profile},{data,error}]=await Promise.all([getCurrentProfile(),supabase.rpc("get_hr_payroll_employee_directory")]);
    if(error) throw error;
    const next=(data??[]) as Employee[];
    setEmployees(next); setCanEdit(profile?.role==="super_admin"||profile?.role==="admin"||profile?.role==="hr");
    if(!employeeId&&next[0]) setEmployeeId(next[0].employee_id);
  }
  async function loadEmployeeData(id:string){
    if(!id){setCompensation([]);setVariablePay([]);setAdvances([]);setDeductions([]);return;}
    const [c,v,a,d]=await Promise.all([
      supabase.from("hr_compensation_records").select("id,employee_id,pay_type,base_rate,currency_code,pay_frequency,standard_weekly_hours,overtime_eligible,overtime_multiplier,effective_from,effective_to,reason").eq("employee_id",id).order("effective_from",{ascending:false}),
      supabase.from("hr_variable_pay").select("id,employee_id,pay_type,amount,earning_date,status,description").eq("employee_id",id).order("earning_date",{ascending:false}).limit(100),
      supabase.from("hr_advances").select("id,employee_id,advance_date,amount,installment_amount,balance_remaining,status,reason").eq("employee_id",id).order("advance_date",{ascending:false}),
      supabase.from("hr_deductions").select("id,employee_id,name,deduction_type,tax_treatment,amount,percentage,frequency,effective_from,effective_to,is_active").eq("employee_id",id).order("effective_from",{ascending:false}),
    ]);
    for(const result of [c,v,a,d]) if(result.error) throw result.error;
    setCompensation((c.data??[]) as Compensation[]); setVariablePay((v.data??[]) as VariablePay[]); setAdvances((a.data??[]) as Advance[]); setDeductions((d.data??[]) as Deduction[]);
  }
  useEffect(()=>{void loadEmployees().catch(e=>setMessage(e instanceof Error?e.message:"Employees could not be loaded.")); // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  useEffect(()=>{void loadEmployeeData(employeeId).catch(e=>setMessage(e instanceof Error?e.message:"Compensation could not be loaded."));},[employeeId]);

  async function saveComp(event:FormEvent){event.preventDefault();if(!canEdit)return;setBusy(true);const {error}=await supabase.from("hr_compensation_records").insert({employee_id:employeeId,pay_type:payType,base_rate:Number(baseRate),currency_code:"USD",pay_frequency:frequency,standard_weekly_hours:Number(weeklyHours),overtime_eligible:overtimeEligible,overtime_multiplier:Number(otMultiplier),effective_from:effectiveFrom,reason:compReason.trim()||null});setBusy(false);if(error)return setMessage(error.message);setBaseRate("");setCompReason("");setMessage("Compensation record added.");await loadEmployeeData(employeeId);}
  async function saveVariable(event:FormEvent){event.preventDefault();if(!canEdit)return;const {error}=await supabase.from("hr_variable_pay").insert({employee_id:employeeId,pay_type:variableType,amount:Number(variableAmount),earning_date:earningDate,status:"approved",description:variableDescription.trim()||null});if(error)return setMessage(error.message);setVariableAmount("");setVariableDescription("");setMessage("Variable pay added.");await loadEmployeeData(employeeId);}
  async function saveAdvance(event:FormEvent){event.preventDefault();if(!canEdit)return;const amount=Number(advanceAmount);const {error}=await supabase.from("hr_advances").insert({employee_id:employeeId,advance_date:advanceDate,amount,balance_remaining:amount,repayment_method:"payroll",installment_amount:installment?Number(installment):null,status:"open",reason:advanceReason.trim()||null});if(error)return setMessage(error.message);setAdvanceAmount("");setInstallment("");setAdvanceReason("");setMessage("Employee advance added.");await loadEmployeeData(employeeId);}
  async function saveDeduction(event:FormEvent){event.preventDefault();if(!canEdit)return;const fixed=deductionType==="fixed";const {error}=await supabase.from("hr_deductions").insert({employee_id:employeeId,name:deductionName.trim(),deduction_type:deductionType,tax_treatment:taxTreatment,amount:fixed?Number(deductionValue):null,percentage:fixed?null:Number(deductionValue),frequency:deductionFrequency,effective_from:deductionStart,is_active:true});if(error)return setMessage(error.message);setDeductionName("");setDeductionValue("");setMessage("Deduction added.");await loadEmployeeData(employeeId);}
  async function voidVariable(id:string){if(!canEdit)return;const {error}=await supabase.from("hr_variable_pay").update({status:"void"}).eq("id",id);if(error)setMessage(error.message);else await loadEmployeeData(employeeId);}
  async function toggleDeduction(row:Deduction){if(!canEdit)return;const {error}=await supabase.from("hr_deductions").update({is_active:!row.is_active}).eq("id",row.id);if(error)setMessage(error.message);else await loadEmployeeData(employeeId);}

  const selected=employees.find(e=>e.employee_id===employeeId);
  const currentComp=useMemo(()=>compensation.find(c=>!c.effective_to||c.effective_to>=new Date().toISOString().slice(0,10)),[compensation]);
  const openAdvance=advances.filter(a=>a.status==="open").reduce((sum,a)=>sum+Number(a.balance_remaining),0);

  return <div className="space-y-6">
    <div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Compensation</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Manage salary/hourly rates, overtime, bonus, commission, advances and deductions.</p></div>
    {message&&<div className={cardClass+" text-sm text-gray-700 dark:text-gray-300"}>{message}</div>}
    {!canEdit&&<div className="rounded-2xl border border-warning-200 bg-warning-50 p-4 text-sm text-warning-800 dark:border-warning-500/30 dark:bg-warning-500/10 dark:text-warning-300">Finance access is read-only for compensation setup. Payroll processing remains available in the payroll module.</div>}
    <div className={cardClass}><label className="block text-sm text-gray-600 dark:text-gray-300">Employee<select className={inputClass+" mt-1 max-w-xl"} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Select employee</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.employee_number} · {e.full_name}</option>)}</select></label>{selected&&<p className="mt-2 text-sm text-gray-500">{selected.position_title||"No position"} · {selected.department_name||"No department"}</p>}</div>
    <div className="grid gap-4 md:grid-cols-3"><div className={cardClass}><p className="text-sm text-gray-500">Current base</p><p className="mt-2 text-xl font-semibold text-gray-800 dark:text-white/90">{currentComp?money.format(Number(currentComp.base_rate)):"Not set"}</p><p className="mt-1 text-xs text-gray-500">{currentComp?`${currentComp.pay_type} · ${currentComp.pay_frequency}`:"Add compensation below"}</p></div><div className={cardClass}><p className="text-sm text-gray-500">Open advances</p><p className="mt-2 text-xl font-semibold text-gray-800 dark:text-white/90">{money.format(openAdvance)}</p></div><div className={cardClass}><p className="text-sm text-gray-500">Active deductions</p><p className="mt-2 text-xl font-semibold text-gray-800 dark:text-white/90">{deductions.filter(d=>d.is_active).length}</p></div></div>

    {canEdit&&<div className="grid gap-6 xl:grid-cols-2">
      <form onSubmit={saveComp} className={cardClass+" space-y-3"><h2 className="font-semibold text-gray-800 dark:text-white/90">New Compensation Rate</h2><div className="grid grid-cols-2 gap-3"><select className={inputClass} value={payType} onChange={e=>setPayType(e.target.value)}><option value="salary">Salary (annual)</option><option value="hourly">Hourly</option></select><input className={inputClass} type="number" min="0" step="0.01" placeholder={payType==="salary"?"Annual salary":"Hourly rate"} value={baseRate} onChange={e=>setBaseRate(e.target.value)} required/></div><div className="grid grid-cols-2 gap-3"><select className={inputClass} value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="semimonthly">Semimonthly</option><option value="monthly">Monthly</option></select><input className={inputClass} type="number" min="1" max="168" step="0.25" value={weeklyHours} onChange={e=>setWeeklyHours(e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><label className="flex h-10 items-center gap-2 text-sm"><input type="checkbox" checked={overtimeEligible} onChange={e=>setOvertimeEligible(e.target.checked)}/> Overtime eligible</label><input className={inputClass} type="number" min="1" step="0.1" value={otMultiplier} onChange={e=>setOtMultiplier(e.target.value)} /></div><input className={inputClass} type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)} /><input className={inputClass} placeholder="Reason (hire, raise, promotion...)" value={compReason} onChange={e=>setCompReason(e.target.value)} /><button disabled={busy||!employeeId} className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white disabled:opacity-50">Add Rate</button></form>
      <form onSubmit={saveVariable} className={cardClass+" space-y-3"><h2 className="font-semibold text-gray-800 dark:text-white/90">Bonus / Commission / Incentive</h2><div className="grid grid-cols-2 gap-3"><select className={inputClass} value={variableType} onChange={e=>setVariableType(e.target.value)}><option value="bonus">Bonus</option><option value="commission">Commission</option><option value="incentive">Incentive</option><option value="reimbursement">Reimbursement</option><option value="other">Other</option></select><input className={inputClass} type="number" min="0" step="0.01" placeholder="Amount" value={variableAmount} onChange={e=>setVariableAmount(e.target.value)} required/></div><input className={inputClass} type="date" value={earningDate} onChange={e=>setEarningDate(e.target.value)} /><input className={inputClass} placeholder="Description" value={variableDescription} onChange={e=>setVariableDescription(e.target.value)} /><button disabled={!employeeId} className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white disabled:opacity-50">Add Variable Pay</button></form>
      <form onSubmit={saveAdvance} className={cardClass+" space-y-3"><h2 className="font-semibold text-gray-800 dark:text-white/90">Employee Advance</h2><div className="grid grid-cols-2 gap-3"><input className={inputClass} type="number" min="0.01" step="0.01" placeholder="Advance amount" value={advanceAmount} onChange={e=>setAdvanceAmount(e.target.value)} required/><input className={inputClass} type="date" value={advanceDate} onChange={e=>setAdvanceDate(e.target.value)} /></div><input className={inputClass} type="number" min="0.01" step="0.01" placeholder="Payroll installment (optional)" value={installment} onChange={e=>setInstallment(e.target.value)} /><input className={inputClass} placeholder="Reason" value={advanceReason} onChange={e=>setAdvanceReason(e.target.value)} /><button disabled={!employeeId} className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white disabled:opacity-50">Add Advance</button></form>
      <form onSubmit={saveDeduction} className={cardClass+" space-y-3"><h2 className="font-semibold text-gray-800 dark:text-white/90">Payroll Deduction</h2><input className={inputClass} placeholder="Deduction name" value={deductionName} onChange={e=>setDeductionName(e.target.value)} required/><div className="grid grid-cols-2 gap-3"><select className={inputClass} value={deductionType} onChange={e=>setDeductionType(e.target.value)}><option value="fixed">Fixed amount</option><option value="percent">Percentage</option></select><input className={inputClass} type="number" min="0" step="0.01" placeholder={deductionType==="fixed"?"Amount":"Percent"} value={deductionValue} onChange={e=>setDeductionValue(e.target.value)} required/></div><div className="grid grid-cols-2 gap-3"><select className={inputClass} value={taxTreatment} onChange={e=>setTaxTreatment(e.target.value)}><option value="pre_tax">Pre-tax</option><option value="post_tax">Post-tax</option></select><select className={inputClass} value={deductionFrequency} onChange={e=>setDeductionFrequency(e.target.value)}><option value="recurring">Recurring</option><option value="one_time">One time</option></select></div><input className={inputClass} type="date" value={deductionStart} onChange={e=>setDeductionStart(e.target.value)} /><button disabled={!employeeId} className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white disabled:opacity-50">Add Deduction</button></form>
    </div>}

    <div className="grid gap-6 xl:grid-cols-2">
      <div className={cardClass}><h2 className="font-semibold text-gray-800 dark:text-white/90">Compensation History</h2><div className="mt-4 space-y-2">{compensation.map(c=><div key={c.id} className="rounded-lg bg-gray-50 p-3 text-sm dark:bg-white/[0.03]"><div className="flex justify-between gap-3"><b>{money.format(Number(c.base_rate))}</b><span className="text-gray-500">{c.effective_from}{c.effective_to?` → ${c.effective_to}`:" → current"}</span></div><p className="mt-1 text-gray-500">{c.pay_type} · {c.pay_frequency} · {Number(c.standard_weekly_hours)}h/week{c.overtime_eligible?` · OT x${Number(c.overtime_multiplier)}`:""}</p></div>)}{compensation.length===0&&<p className="mt-4 text-sm text-gray-500">No compensation history.</p>}</div></div>
      <div className={cardClass}><h2 className="font-semibold text-gray-800 dark:text-white/90">Variable Pay</h2><div className="mt-4 space-y-2">{variablePay.map(v=><div key={v.id} className="flex items-center justify-between rounded-lg bg-gray-50 p-3 text-sm dark:bg-white/[0.03]"><div><b className="capitalize">{v.pay_type}</b> · {money.format(Number(v.amount))}<p className="text-xs text-gray-500">{v.earning_date} · {v.status}{v.description?` · ${v.description}`:""}</p></div>{canEdit&&v.status!=="paid"&&v.status!=="void"?<button onClick={()=>void voidVariable(v.id)} className="text-xs text-error-600">Void</button>:null}</div>)}</div></div>
      <div className={cardClass}><h2 className="font-semibold text-gray-800 dark:text-white/90">Advances</h2><div className="mt-4 space-y-2">{advances.map(a=><div key={a.id} className="rounded-lg bg-gray-50 p-3 text-sm dark:bg-white/[0.03]"><div className="flex justify-between"><b>{money.format(Number(a.amount))}</b><span className="capitalize text-gray-500">{a.status}</span></div><p className="mt-1 text-xs text-gray-500">Balance {money.format(Number(a.balance_remaining))}{a.installment_amount?` · ${money.format(Number(a.installment_amount))}/payroll`:""}{a.reason?` · ${a.reason}`:""}</p></div>)}</div></div>
      <div className={cardClass}><h2 className="font-semibold text-gray-800 dark:text-white/90">Deductions</h2><div className="mt-4 space-y-2">{deductions.map(d=><div key={d.id} className="flex items-center justify-between rounded-lg bg-gray-50 p-3 text-sm dark:bg-white/[0.03]"><div><b>{d.name}</b><p className="text-xs text-gray-500">{d.deduction_type==="fixed"?money.format(Number(d.amount||0)):`${Number(d.percentage||0)}%`} · {d.tax_treatment.replace("_","-")} · {d.frequency}</p></div>{canEdit?<button onClick={()=>void toggleDeduction(d)} className="text-xs font-medium text-brand-600">{d.is_active?"Disable":"Enable"}</button>:<span className="text-xs text-gray-500">{d.is_active?"Active":"Inactive"}</span>}</div>)}</div></div>
    </div>
  </div>;
}
