"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { supabase } from "@/lib/supabase/client";

type Employee={id:string;employee_number:string;first_name:string;last_name:string};
type HrDocument={id:string;employee_id:string;document_type:string;title:string;storage_path:string|null;file_name:string|null;mime_type:string|null;file_size:number|null;document_number:string|null;issued_on:string|null;expires_on:string|null;status:string;is_confidential:boolean;notes:string|null;created_at:string};
const input="h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 focus:border-brand-300 focus:outline-none focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90";
const card="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]";
const types=["employment_contract","w4","i9","id","work_authorization","certification","license","policy_acknowledgment","performance","medical","other"];
function safeName(value:string){return value.replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-");}
function bytes(value:number|null){if(!value)return "—";if(value<1024)return `${value} B`;if(value<1048576)return `${(value/1024).toFixed(1)} KB`;return `${(value/1048576).toFixed(1)} MB`;}

export default function DocumentsManager(){
 const [employees,setEmployees]=useState<Employee[]>([]);const [documents,setDocuments]=useState<HrDocument[]>([]);const [employeeId,setEmployeeId]=useState("");const [type,setType]=useState("employment_contract");const [title,setTitle]=useState("");const [documentNumber,setDocumentNumber]=useState("");const [issuedOn,setIssuedOn]=useState("");const [expiresOn,setExpiresOn]=useState("");const [notes,setNotes]=useState("");const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);
 async function load(){const [e,d]=await Promise.all([supabase.from("hr_employees").select("id,employee_number,first_name,last_name").order("last_name"),supabase.from("hr_documents").select("id,employee_id,document_type,title,storage_path,file_name,mime_type,file_size,document_number,issued_on,expires_on,status,is_confidential,notes,created_at").order("created_at",{ascending:false}).limit(500)]);if(e.error)throw e.error;if(d.error)throw d.error;const es=(e.data??[]) as Employee[];setEmployees(es);setDocuments((d.data??[]) as HrDocument[]);if(!employeeId&&es[0])setEmployeeId(es[0].id);}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Documents could not be loaded.")); // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 async function upload(ev:FormEvent){ev.preventDefault();if(!employeeId||!file)return;setBusy(true);setMessage(null);const path=`${employeeId}/${crypto.randomUUID()}-${safeName(file.name)}`;const uploadResult=await supabase.storage.from("hr-documents").upload(path,file,{contentType:file.type||undefined,upsert:false});if(uploadResult.error){setBusy(false);return setMessage(uploadResult.error.message);}const {error}=await supabase.from("hr_documents").insert({employee_id:employeeId,document_type:type,title:title.trim()||file.name,storage_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size,document_number:documentNumber.trim()||null,issued_on:issuedOn||null,expires_on:expiresOn||null,status:"active",is_confidential:true,notes:notes.trim()||null});if(error){await supabase.storage.from("hr-documents").remove([path]);setBusy(false);return setMessage(error.message);}setBusy(false);setFile(null);setTitle("");setDocumentNumber("");setIssuedOn("");setExpiresOn("");setNotes("");const inputEl=document.getElementById("hr-document-file") as HTMLInputElement|null;if(inputEl)inputEl.value="";setMessage("Document uploaded securely.");await load();}
 async function openDocument(row:HrDocument){if(!row.storage_path)return;const {data,error}=await supabase.storage.from("hr-documents").createSignedUrl(row.storage_path,60);if(error)return setMessage(error.message);window.open(data.signedUrl,"_blank","noopener,noreferrer");}
 async function remove(row:HrDocument){if(!window.confirm(`Delete ${row.title}?`))return;if(row.storage_path){const storageResult=await supabase.storage.from("hr-documents").remove([row.storage_path]);if(storageResult.error)return setMessage(storageResult.error.message);}const {error}=await supabase.from("hr_documents").delete().eq("id",row.id);if(error)setMessage(error.message);else await load();}
 const employeeMap=useMemo(()=>new Map(employees.map(e=>[e.id,`${e.employee_number} · ${e.first_name} ${e.last_name}`])),[employees]);const filtered=employeeId?documents.filter(d=>d.employee_id===employeeId):documents;const today=new Date();const soon=new Date();soon.setDate(today.getDate()+60);const expiring=documents.filter(d=>d.expires_on&&new Date(d.expires_on)>=today&&new Date(d.expires_on)<=soon).length;const expired=documents.filter(d=>d.expires_on&&new Date(d.expires_on)<today&&d.status==="active").length;
 return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Employee Documents</h1><p className="mt-1 text-sm text-gray-500">Private employee files, W-4/I-9 records, contracts, licenses and expiration tracking.</p></div>{message&&<div className={card+" text-sm"}>{message}</div>}
 <div className="grid gap-4 sm:grid-cols-3"><div className={card}><p className="text-sm text-gray-500">Documents</p><p className="mt-2 text-2xl font-semibold">{documents.length}</p></div><div className={card}><p className="text-sm text-gray-500">Expiring in 60 days</p><p className="mt-2 text-2xl font-semibold">{expiring}</p></div><div className={card}><p className="text-sm text-gray-500">Expired</p><p className="mt-2 text-2xl font-semibold">{expired}</p></div></div>
 <div className="grid gap-6 xl:grid-cols-[380px_1fr]"><form onSubmit={upload} className={card+" space-y-3"}><h2 className="font-semibold text-gray-800 dark:text-white/90">Upload Document</h2><select className={input} value={employeeId} onChange={e=>setEmployeeId(e.target.value)} required>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_number} · {e.first_name} {e.last_name}</option>)}</select><select className={input} value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t} value={t}>{t.replaceAll("_"," ")}</option>)}</select><input className={input} placeholder="Document title" value={title} onChange={e=>setTitle(e.target.value)}/><input className={input} placeholder="Document / license number (optional)" value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)}/><div className="grid grid-cols-2 gap-3"><label className="text-xs text-gray-500">Issued<input className={input+" mt-1"} type="date" value={issuedOn} onChange={e=>setIssuedOn(e.target.value)}/></label><label className="text-xs text-gray-500">Expires<input className={input+" mt-1"} type="date" value={expiresOn} onChange={e=>setExpiresOn(e.target.value)}/></label></div><input id="hr-document-file" type="file" onChange={e=>setFile(e.target.files?.[0]??null)} required className="block w-full text-sm text-gray-600 file:mr-3 file:rounded-lg file:border-0 file:bg-brand-50 file:px-3 file:py-2 file:text-brand-700 dark:text-gray-300"/><textarea className="min-h-20 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90" placeholder="Notes" value={notes} onChange={e=>setNotes(e.target.value)}/><p className="text-xs text-gray-500">Private bucket · max 15 MB · PDF, images, TXT and Word documents.</p><button disabled={busy||!file} className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white disabled:opacity-50">{busy?"Uploading...":"Upload Securely"}</button></form>
 <div className={card+" overflow-hidden p-0"}><div className="border-b border-gray-200 p-4 dark:border-gray-800"><select className={input+" max-w-md"} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">All employees</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_number} · {e.first_name} {e.last_name}</option>)}</select></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-white/[0.02]"><tr><th className="px-4 py-3">Document</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Expires</th><th className="px-4 py-3">Size</th><th className="px-4 py-3"></th></tr></thead><tbody>{filtered.map(d=><tr key={d.id} className="border-t border-gray-100 dark:border-gray-800"><td className="px-4 py-3"><button onClick={()=>void openDocument(d)} className="font-medium text-brand-600 hover:underline">{d.title}</button><p className="text-xs text-gray-500">{d.file_name||"metadata only"}</p></td><td className="px-4 py-3 capitalize">{d.document_type.replaceAll("_"," ")}</td><td className="px-4 py-3">{employeeMap.get(d.employee_id)||d.employee_id}</td><td className="px-4 py-3">{d.expires_on||"—"}</td><td className="px-4 py-3">{bytes(d.file_size)}</td><td className="px-4 py-3 text-right"><button onClick={()=>void remove(d)} className="text-xs text-error-600">Delete</button></td></tr>)}{filtered.length===0&&<tr><td colSpan={6} className="px-4 py-10 text-center text-gray-500">No documents found.</td></tr>}</tbody></table></div></div></div></div>;
}
