"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { supabase } from "@/lib/supabase/client";

type Employee={id:string;employee_number:string;first_name:string;last_name:string;employment_status:string};
type Task={id:string;employee_id:string;task_type:string;title:string;description:string|null;due_date:string|null;completed_at:string|null;status:string;sort_order:number};
const input="h-10 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 focus:border-brand-300 focus:outline-none focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90";
const card="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]";
const onboarding=["Complete employment documents","Complete W-4 and I-9 workflow","Create system access","Assign equipment / workspace","Benefits enrollment review","Orientation and policy acknowledgment","Manager introduction / first-week plan"];
const offboarding=["Confirm final working date","Collect company equipment","Disable system access","Final payroll / deductions review","Benefits termination / continuation review","Exit interview","Archive employment records"];

export default function EmployeeTasksManager(){
 const [employees,setEmployees]=useState<Employee[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [employeeId,setEmployeeId]=useState("");const [taskType,setTaskType]=useState("onboarding");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [dueDate,setDueDate]=useState("");const [message,setMessage]=useState<string|null>(null);
 async function load(){const [e,t]=await Promise.all([supabase.from("hr_employees").select("id,employee_number,first_name,last_name,employment_status").order("last_name"),supabase.from("hr_employee_tasks").select("id,employee_id,task_type,title,description,due_date,completed_at,status,sort_order").order("status").order("due_date")]);if(e.error)throw e.error;if(t.error)throw t.error;const es=(e.data??[]) as Employee[];setEmployees(es);setTasks((t.data??[]) as Task[]);if(!employeeId&&es[0])setEmployeeId(es[0].id);}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:"Tasks could not be loaded.")); // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 async function addTask(ev:FormEvent){ev.preventDefault();const {error}=await supabase.from("hr_employee_tasks").insert({employee_id:employeeId,task_type:taskType,title:title.trim(),description:description.trim()||null,due_date:dueDate||null,status:"pending"});if(error)return setMessage(error.message);setTitle("");setDescription("");setDueDate("");setMessage("Task added.");await load();}
 async function applyTemplate(kind:"onboarding"|"offboarding"){if(!employeeId)return;const template=kind==="onboarding"?onboarding:offboarding;const existing=new Set(tasks.filter(t=>t.employee_id===employeeId&&t.task_type===kind).map(t=>t.title));const rows=template.filter(x=>!existing.has(x)).map((title,index)=>({employee_id:employeeId,task_type:kind,title,status:"pending",sort_order:(index+1)*10}));if(!rows.length)return setMessage("Template tasks already exist for this employee.");const {error}=await supabase.from("hr_employee_tasks").insert(rows);if(error)setMessage(error.message);else{setMessage(`${rows.length} ${kind} task(s) added.`);await load();}}
 async function setStatus(row:Task,status:string){const {error}=await supabase.from("hr_employee_tasks").update({status,completed_at:status==="completed"?new Date().toISOString():null}).eq("id",row.id);if(error)setMessage(error.message);else await load();}
 async function remove(id:string){if(!window.confirm("Delete this task?"))return;const {error}=await supabase.from("hr_employee_tasks").delete().eq("id",id);if(error)setMessage(error.message);else await load();}
 const employeeMap=useMemo(()=>new Map(employees.map(e=>[e.id,`${e.employee_number} · ${e.first_name} ${e.last_name}`])),[employees]);const filtered=employeeId?tasks.filter(t=>t.employee_id===employeeId):tasks;const pending=tasks.filter(t=>t.status==="pending"||t.status==="in_progress").length;const overdue=tasks.filter(t=>t.status!=="completed"&&t.status!=="cancelled"&&t.due_date&&new Date(t.due_date)<new Date()).length;
 return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Onboarding & Offboarding</h1><p className="mt-1 text-sm text-gray-500">Standardize employee start, transition and exit workflows.</p></div>{message&&<div className={card+" text-sm"}>{message}</div>}<div className="grid gap-4 sm:grid-cols-2"><div className={card}><p className="text-sm text-gray-500">Open tasks</p><p className="mt-2 text-2xl font-semibold">{pending}</p></div><div className={card}><p className="text-sm text-gray-500">Overdue tasks</p><p className="mt-2 text-2xl font-semibold">{overdue}</p></div></div>
 <div className={card}><div className="flex flex-wrap items-end gap-3"><label className="min-w-72 flex-1 text-sm text-gray-600">Employee<select className={input+" mt-1"} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.employee_number} · {e.first_name} {e.last_name} · {e.employment_status}</option>)}</select></label><button onClick={()=>void applyTemplate("onboarding")} className="h-10 rounded-lg border border-gray-300 px-3 text-sm font-medium dark:border-gray-700">Apply Onboarding Template</button><button onClick={()=>void applyTemplate("offboarding")} className="h-10 rounded-lg border border-gray-300 px-3 text-sm font-medium dark:border-gray-700">Apply Offboarding Template</button></div></div>
 <div className="grid gap-6 xl:grid-cols-[380px_1fr]"><form onSubmit={addTask} className={card+" space-y-3"}><h2 className="font-semibold text-gray-800 dark:text-white/90">Add Task</h2><select className={input} value={taskType} onChange={e=>setTaskType(e.target.value)}><option value="onboarding">Onboarding</option><option value="offboarding">Offboarding</option><option value="general">General</option></select><input className={input} placeholder="Task title" value={title} onChange={e=>setTitle(e.target.value)} required/><textarea className="min-h-20 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90" placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><input className={input} type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/><button disabled={!employeeId} className="h-10 rounded-lg bg-brand-500 px-4 text-sm font-medium text-white disabled:opacity-50">Add Task</button></form>
 <div className={card+" overflow-hidden p-0"}><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500 dark:bg-white/[0.02]"><tr><th className="px-4 py-3">Task</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="border-t border-gray-100 dark:border-gray-800"><td className="px-4 py-3"><b>{t.title}</b>{!employeeId&&<p className="text-xs text-gray-500">{employeeMap.get(t.employee_id)||t.employee_id}</p>}{t.description&&<p className="text-xs text-gray-500">{t.description}</p>}</td><td className="px-4 py-3 capitalize">{t.task_type}</td><td className="px-4 py-3">{t.due_date||"—"}</td><td className="px-4 py-3 capitalize">{t.status.replace("_"," ")}</td><td className="px-4 py-3"><div className="flex justify-end gap-2">{t.status!=="completed"&&<button onClick={()=>void setStatus(t,"completed")} className="text-xs text-success-600">Complete</button>}{t.status==="pending"&&<button onClick={()=>void setStatus(t,"in_progress")} className="text-xs text-brand-600">Start</button>}<button onClick={()=>void remove(t.id)} className="text-xs text-error-600">Delete</button></div></td></tr>)}{filtered.length===0&&<tr><td colSpan={5} className="px-4 py-10 text-center text-gray-500">No tasks for this employee.</td></tr>}</tbody></table></div></div></div></div>;
}
