"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase/client";

type Employee={id:string;department_id:string|null;employment_status:string;hire_date:string|null;termination_date:string|null};
type Department={id:string;name:string};
type Attendance={employee_id:string;work_date:string;regular_hours:number;overtime_hours:number;status:string};
type LeaveBalance={entitled_hours:number;carried_hours:number;adjusted_hours:number;used_hours:number;pending_hours:number};
type Document={expires_on:string|null;status:string};
type Task={status:string;due_date:string|null};
type PayrollItem={gross_pay:number;net_pay:number;total_employer_cost:number};
const card="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]";
const number=new Intl.NumberFormat("en-US",{maximumFractionDigits:2});
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export default function HrReports(){
 const [employees,setEmployees]=useState<Employee[]>([]);const [departments,setDepartments]=useState<Department[]>([]);const [attendance,setAttendance]=useState<Attendance[]>([]);const [balances,setBalances]=useState<LeaveBalance[]>([]);const [documents,setDocuments]=useState<Document[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [payroll,setPayroll]=useState<PayrollItem[]>([]);const [message,setMessage]=useState<string|null>(null);
 useEffect(()=>{const now=new Date();const monthStart=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10);const yearStart=`${now.getFullYear()}-01-01`;async function load(){const [e,d,a,b,doc,t,p]=await Promise.all([supabase.from("hr_employees").select("id,department_id,employment_status,hire_date,termination_date"),supabase.from("hr_departments").select("id,name"),supabase.from("hr_attendance_records").select("employee_id,work_date,regular_hours,overtime_hours,status").gte("work_date",monthStart),supabase.from("hr_leave_balances").select("entitled_hours,carried_hours,adjusted_hours,used_hours,pending_hours").eq("balance_year",now.getFullYear()),supabase.from("hr_documents").select("expires_on,status"),supabase.from("hr_employee_tasks").select("status,due_date"),supabase.from("hr_payroll_items").select("gross_pay,net_pay,total_employer_cost").gte("created_at",yearStart)]);for(const r of [e,d,a,b,doc,t,p])if(r.error)throw r.error;setEmployees((e.data??[]) as Employee[]);setDepartments((d.data??[]) as Department[]);setAttendance((a.data??[]) as Attendance[]);setBalances((b.data??[]) as LeaveBalance[]);setDocuments((doc.data??[]) as Document[]);setTasks((t.data??[]) as Task[]);setPayroll((p.data??[]) as PayrollItem[]);}void load().catch(e=>setMessage(e instanceof Error?e.message:"HR reports could not be loaded."));},[]);
 const now=new Date();const y=now.getFullYear();const active=employees.filter(e=>e.employment_status==="active"||e.employment_status==="on_leave").length;const hires=employees.filter(e=>e.hire_date&&new Date(e.hire_date).getFullYear()===y).length;const terms=employees.filter(e=>e.termination_date&&new Date(e.termination_date).getFullYear()===y).length;const regHours=attendance.reduce((s,a)=>s+Number(a.regular_hours||0),0);const otHours=attendance.reduce((s,a)=>s+Number(a.overtime_hours||0),0);const absent=attendance.filter(a=>a.status==="absent"||a.status==="no_show").length;const late=attendance.filter(a=>a.status==="late").length;const leaveAvailable=balances.reduce((s,b)=>s+Number(b.entitled_hours)+Number(b.carried_hours)+Number(b.adjusted_hours)-Number(b.used_hours)-Number(b.pending_hours),0);const soon=new Date();soon.setDate(now.getDate()+60);const expiring=documents.filter(d=>d.expires_on&&new Date(d.expires_on)>=now&&new Date(d.expires_on)<=soon).length;const openTasks=tasks.filter(t=>t.status==="pending"||t.status==="in_progress").length;const payrollTotals=payroll.reduce((a,p)=>({gross:a.gross+Number(p.gross_pay||0),net:a.net+Number(p.net_pay||0),cost:a.cost+Number(p.total_employer_cost||0)}),{gross:0,net:0,cost:0});const departmentCounts=useMemo(()=>departments.map(d=>({name:d.name,count:employees.filter(e=>e.department_id===d.id&&(e.employment_status==="active"||e.employment_status==="on_leave")).length})).sort((a,b)=>b.count-a.count),[departments,employees]);
 const rows=[["Active headcount",active],["Hires YTD",hires],["Terminations YTD",terms],["Regular hours this month",number.format(regHours)],["Overtime this month",number.format(otHours)],["Absent / no-show this month",absent],["Late records this month",late],["Available leave hours",number.format(leaveAvailable)],["Documents expiring ≤60 days",expiring],["Open lifecycle tasks",openTasks],["Payroll gross YTD",money.format(payrollTotals.gross)],["Payroll employer cost YTD",money.format(payrollTotals.cost)]];
 return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">HR Reports</h1><p className="mt-1 text-sm text-gray-500">Workforce, attendance, leave, compliance and payroll indicators.</p></div>{message&&<div className={card+" text-sm"}>{message}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{rows.map(([label,value])=><div key={String(label)} className={card}><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-xl font-semibold text-gray-800 dark:text-white/90">{value}</p></div>)}</div><div className="grid gap-6 xl:grid-cols-2"><div className={card}><h2 className="font-semibold text-gray-800 dark:text-white/90">Headcount by Department</h2><div className="mt-4 space-y-3">{departmentCounts.map(row=><div key={row.name} className="flex items-center justify-between border-b border-gray-100 pb-2 text-sm dark:border-gray-800"><span>{row.name}</span><b>{row.count}</b></div>)}{departmentCounts.length===0&&<p className="text-sm text-gray-500">No departments configured.</p>}</div></div><div className={card}><h2 className="font-semibold text-gray-800 dark:text-white/90">Payroll YTD</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span>Gross payroll</span><b>{money.format(payrollTotals.gross)}</b></div><div className="flex justify-between"><span>Net payroll</span><b>{money.format(payrollTotals.net)}</b></div><div className="flex justify-between border-t border-gray-100 pt-3 dark:border-gray-800"><span>Total employer cost</span><b>{money.format(payrollTotals.cost)}</b></div></div><p className="mt-4 text-xs text-gray-500">Payroll totals reflect recorded payroll items. Tax accuracy depends on verified tax inputs until the automated US tax engine is enabled.</p></div></div></div>;
}
