import type { UserRole } from "@/lib/supabase/profile";

export type TrainingCategory =
  | "Getting Started"
  | "Sales & Customers"
  | "Inventory & Warehouse"
  | "Shipping & Installation"
  | "Finance"
  | "Personnel & HR"
  | "Administration"
  | "Reports & Controls";

export type TrainingLesson = {
  id: string;
  title: string;
  category: TrainingCategory;
  summary: string;
  roles: UserRole[];
  durationMinutes: number;
  path?: string;
  steps: string[];
  bestPractices?: string[];
  warnings?: string[];
};

const admins: UserRole[] = ["super_admin", "admin"];
const allRoles: UserRole[] = ["super_admin", "admin", "sales", "finance", "hr", "warehouse", "shipping"];

export const TRAINING_LESSONS: TrainingLesson[] = [
  {
    id: "getting-started-navigation",
    title: "Getting Started & Navigation",
    category: "Getting Started",
    summary: "Learn how the admin panel is organized, how permissions affect the sidebar, and how to move safely between modules.",
    roles: allRoles,
    durationMinutes: 5,
    steps: [
      "Sign in with your assigned account. Never share credentials with another employee.",
      "Use the left sidebar to access modules available to your role. Missing menu items normally mean the role does not have permission.",
      "Use breadcrumbs to understand where you are and return to the previous module.",
      "Use filters and search before scrolling long tables.",
      "When a page says Access Restricted, do not try to work around it; ask an Admin to review the role assignment.",
    ],
    bestPractices: [
      "Keep one browser session per user so audit trails remain attributable.",
      "Refresh the page after a role change so the permission cache is renewed.",
    ],
  },
  {
    id: "security-roles",
    title: "Security, Roles & Approvals",
    category: "Getting Started",
    summary: "Understand why some actions are read-only and when an approval request is required.",
    roles: allRoles,
    durationMinutes: 6,
    path: "/approvals",
    steps: [
      "Treat page visibility and action permission as separate concepts: seeing an order does not always mean you may edit it.",
      "When a commercial exception triggers approval, submit the request instead of bypassing the workflow.",
      "Only authorized Admin roles can approve or reject protected approval requests.",
      "Finance may view approval context but cannot approve or reject requests.",
      "Warehouse and Shipping users should use operational shipment/stock workflows rather than editing commercial order data.",
    ],
    warnings: [
      "Never use another person's account to obtain permissions you do not have.",
      "Do not manually alter database records to bypass approval rules.",
    ],
  },
  {
    id: "customers-master",
    title: "Customer Master Data",
    category: "Sales & Customers",
    summary: "Create and maintain clean customer records before starting orders or invoices.",
    roles: [...admins, "sales"],
    durationMinutes: 8,
    path: "/customers",
    steps: [
      "Search existing customers before creating a new record to avoid duplicates.",
      "Open the customer record and verify company/contact details, billing information and commercial settings.",
      "Update only information you can verify from the customer or approved internal source.",
      "If a protected commercial change requires approval, submit the request and wait for approval before relying on it.",
      "Review the customer record before creating a new order.",
    ],
    bestPractices: ["Use consistent legal/company names and complete contact details."],
  },
  {
    id: "orders-create-edit",
    title: "Create & Edit Orders",
    category: "Sales & Customers",
    summary: "Build customer orders, use the searchable product picker, select pricing correctly and understand when edits require approval.",
    roles: [...admins, "sales"],
    durationMinutes: 12,
    path: "/customers/orders",
    steps: [
      "Open Customers → Orders and choose New Order.",
      "Select the customer and confirm fulfillment type: customer pickup, delivery, or delivery + installation.",
      "Use the product picker lightbox to search/filter products and add multiple items efficiently.",
      "Confirm quantities and the assigned price group. Sales users must never use cost as a selling price.",
      "Review discounts, manual prices, margin warnings, FOB/restricted pricing and other approval-sensitive conditions.",
      "Save the order and verify totals before confirming it.",
      "For a confirmed order, use the controlled revision workflow; protected changes create an approval request instead of silently changing the live order.",
    ],
    warnings: [
      "Do not bypass below-cost or margin warnings.",
      "Do not change confirmed orders through direct database edits.",
    ],
  },
  {
    id: "pricing-approvals",
    title: "Pricing, Margin & Commercial Exceptions",
    category: "Sales & Customers",
    summary: "Understand selling prices, price groups, margin controls and approval-sensitive exceptions.",
    roles: [...admins, "sales", "finance"],
    durationMinutes: 10,
    path: "/pricing/dashboard",
    steps: [
      "Use Pricing Dashboard/Product Prices to review active selling prices.",
      "Use the customer's approved price group when creating an order.",
      "Treat Pickup Level as a normal selectable price group when configured for the customer/order.",
      "If margin, below-cost, manual pricing, discount, commission override, FOB or restricted group rules trigger approval, submit the approval request.",
      "Finance may review cost and margin context; Sales should not see product cost.",
    ],
    warnings: ["Never expose internal cost/margin information to unauthorized users or customers."],
  },
  {
    id: "invoices-collections",
    title: "Invoices & Collections",
    category: "Finance",
    summary: "Create invoices from orders, record collections and use the controlled invoice state workflow.",
    roles: [...admins, "sales", "finance"],
    durationMinutes: 10,
    path: "/customers/invoices",
    steps: [
      "Open the order/customer context and create the invoice using the controlled invoice workflow.",
      "Verify customer, invoice lines, taxes, totals and payment status before saving.",
      "Record collections/payments through the invoice workflow rather than direct table updates.",
      "Use approved invoice state transitions. Protected voids or paid-amount reductions may require approval.",
      "Review the invoice after every collection entry to confirm paid and outstanding balances.",
    ],
    warnings: ["Do not reduce paid amounts or void protected invoices outside the approval workflow."],
  },
  {
    id: "inventory-overview",
    title: "Inventory & Low Stock",
    category: "Inventory & Warehouse",
    summary: "Read on-hand, reserved and available stock correctly and use low-stock reporting.",
    roles: [...admins, "sales", "finance", "warehouse", "shipping"],
    durationMinutes: 7,
    path: "/inventory",
    steps: [
      "Open Inventory → Stock Overview to review quantities by product/location.",
      "Remember that available stock is on-hand quantity minus reserved quantity.",
      "Use Low Stock to identify products at or below configured minimum stock.",
      "Use Stock Movements to understand why inventory changed before making a correction.",
      "Only users with inventory management permission should run stock operations.",
    ],
  },
  {
    id: "stock-operations",
    title: "Stock Operations",
    category: "Inventory & Warehouse",
    summary: "Perform receiving, stock-out and adjustments without corrupting inventory history.",
    roles: [...admins, "warehouse"],
    durationMinutes: 10,
    path: "/stock-operations",
    steps: [
      "Select the correct warehouse/location before recording movement.",
      "Scan or select the correct product/SKU and verify the product description.",
      "Choose the correct stock operation type and enter the actual physical quantity.",
      "Add a useful reference/note when the movement is not self-explanatory.",
      "Complete the operation once and verify the Stock Movements log afterward.",
    ],
    warnings: ["Do not create a second movement to 'fix' a typo before checking whether a controlled adjustment is more appropriate."],
  },
  {
    id: "qr-operations",
    title: "QR & Shelf Operations",
    category: "Inventory & Warehouse",
    summary: "Use warehouse, zone, location and product QR codes safely during physical stock work.",
    roles: [...admins, "warehouse"],
    durationMinutes: 9,
    path: "/scan",
    steps: [
      "Scan warehouse QR first when the workflow requires warehouse context.",
      "Scan zone/location QR and verify the recognized location before scanning products.",
      "Scan the product QR/SKU and confirm the recognized product before entering quantity.",
      "Complete the shelf/stock action only after all three contexts are correct.",
      "Use QR Labels to reprint labels when needed; avoid manually inventing QR values.",
    ],
    warnings: ["Shipping can view QR labels but should not perform general QR stock operations."],
  },
  {
    id: "shipments",
    title: "Shipment Execution",
    category: "Shipping & Installation",
    summary: "Process shipments using shipment-specific workflows without broad order or customer editing access.",
    roles: [...admins, "sales", "warehouse", "shipping"],
    durationMinutes: 9,
    path: "/customers/shipments",
    steps: [
      "Open the shipment queue and locate the correct order/shipment reference.",
      "Verify products, quantities and destination information supplied by the shipment workflow.",
      "Use shipment actions to advance operational status instead of editing the commercial order directly.",
      "Confirm physical handoff/loading before marking the corresponding shipment status.",
      "Report quantity or item discrepancies before completing shipment.",
    ],
  },
  {
    id: "installations",
    title: "Delivery & Installation Workflow",
    category: "Shipping & Installation",
    summary: "Schedule and manage installation work only for orders that include installation fulfillment.",
    roles: [...admins, "sales"],
    durationMinutes: 7,
    path: "/customers/installations",
    steps: [
      "Confirm the order fulfillment type is delivery + installation.",
      "Open Installations and locate the related customer order.",
      "Schedule installation using confirmed customer/logistics information.",
      "Update installation status as work is scheduled, performed or requires follow-up.",
      "Keep shipment and installation status aligned with what actually happened in the field.",
    ],
  },
  {
    id: "finance-cost-margin",
    title: "Cost & Margin Review",
    category: "Finance",
    summary: "Review product cost and estimated margin without changing protected cost data from the Finance role.",
    roles: [...admins, "finance"],
    durationMinutes: 7,
    path: "/pricing/cost-margin",
    steps: [
      "Use Cost & Margin to review current unit cost and selling-price context.",
      "Treat historical profit estimates carefully when historical order lines do not snapshot historical cost.",
      "Use margin warnings to investigate commercial risk before an order proceeds.",
      "Finance access to compensation/cost setup is intentionally read-only where configured.",
    ],
    warnings: ["Do not present current-cost estimates as audited historical COGS when historical cost was not snapshotted."],
  },
  {
    id: "finance-settings",
    title: "Tax Rules & Payment Methods",
    category: "Finance",
    summary: "Maintain financial configuration without changing unrelated General Settings.",
    roles: [...admins, "finance"],
    durationMinutes: 7,
    path: "/settings/general/tax-rules",
    steps: [
      "Use Finance → Tax Rules for configured sales-tax behavior.",
      "Use Finance → Payment Methods to maintain allowed customer payment methods.",
      "Verify changes before saving because these settings affect downstream financial workflows.",
      "Use General Settings only when your role explicitly permits it; Finance does not receive broad system settings access.",
    ],
    warnings: ["Do not guess tax rates. Use verified jurisdiction/rule data."],
  },
  {
    id: "payroll-processing",
    title: "Payroll Processing",
    category: "Finance",
    summary: "Prepare payroll periods and runs, review earnings/deductions and move payroll through its controlled workflow.",
    roles: [...admins, "finance", "hr"],
    durationMinutes: 14,
    path: "/finance/payroll",
    steps: [
      "Create/select the correct payroll period and verify period start, period end and pay date.",
      "Prepare the payroll run so employee compensation, attendance/overtime, variable pay, benefits, advances and deductions are included.",
      "Review each employee payroll item before approval.",
      "Enter/verify federal, state, local, Social Security and Medicare values using the approved payroll process.",
      "Confirm gross pay, taxable wages, deductions, taxes, net pay and employer cost.",
      "Approve the payroll run only after review, then mark paid only after payment has actually been executed.",
    ],
    warnings: [
      "Automatic US payroll tax calculation is not yet the source of truth; tax values require verified tax-engine/manual review until the dedicated engine is implemented.",
      "Never mark a payroll run paid before funds are actually released.",
    ],
  },
  {
    id: "hr-employee-master",
    title: "Employee Master",
    category: "Personnel & HR",
    summary: "Create and maintain the core employee record used by every HR module.",
    roles: [...admins, "hr"],
    durationMinutes: 10,
    path: "/personnel/employees",
    steps: [
      "Search existing employees before creating a new record.",
      "Enter identity/contact details, employment type/status, hire date and work location.",
      "Assign the correct department, position and manager.",
      "Link a system user account only when the employee needs application access.",
      "Use termination fields when employment ends instead of deleting the employee record.",
    ],
    bestPractices: ["Keep salary, payroll, tax and document data in their dedicated HR modules rather than free-text notes."],
  },
  {
    id: "hr-attendance",
    title: "Attendance & Time",
    category: "Personnel & HR",
    summary: "Record regular hours, overtime, lateness, absence and no-show status accurately.",
    roles: [...admins, "hr"],
    durationMinutes: 9,
    path: "/personnel/attendance",
    steps: [
      "Select the employee and work date.",
      "Record clock-in/clock-out or regular/overtime hours according to the available workflow.",
      "Choose the correct attendance status for absence, leave, holiday, remote work or no-show.",
      "Review overtime and exception records before payroll preparation.",
      "Correct attendance before payroll is approved whenever possible.",
    ],
  },
  {
    id: "hr-leave",
    title: "Leave & PTO",
    category: "Personnel & HR",
    summary: "Maintain leave policies, balances and requests without losing auditability.",
    roles: [...admins, "hr"],
    durationMinutes: 10,
    path: "/personnel/leave",
    steps: [
      "Confirm the employee has the correct leave type/balance for the year.",
      "Review pending leave requests and verify dates/hours.",
      "Approve or reject the request according to company policy.",
      "Monitor pending, used and remaining balances.",
      "Use annual grant, monthly accrual or per-payroll accrual according to the configured leave policy.",
    ],
  },
  {
    id: "hr-compensation",
    title: "Employee Compensation",
    category: "Personnel & HR",
    summary: "Maintain effective-dated salary/hourly rates, overtime eligibility, bonus/commission, advances and deductions.",
    roles: [...admins, "hr", "finance"],
    durationMinutes: 12,
    path: "/personnel/compensation",
    steps: [
      "Select the employee and review current compensation history before adding a new rate.",
      "Choose salary or hourly pay and enter the effective date and pay frequency.",
      "Set standard weekly hours and overtime eligibility/multiplier when applicable.",
      "Record approved bonus, commission, incentive or reimbursement in Variable Pay.",
      "Record employee advances with the intended payroll installment when repayment is through payroll.",
      "Configure fixed/percentage deductions and pre-tax/post-tax treatment as appropriate.",
    ],
    warnings: ["Finance can review compensation but should not modify compensation setup when using the Finance role."],
  },
  {
    id: "hr-benefits-documents",
    title: "Benefits & Employee Documents",
    category: "Personnel & HR",
    summary: "Manage benefit enrollment and private employee files with expiration awareness.",
    roles: [...admins, "hr"],
    durationMinutes: 11,
    path: "/personnel/benefits",
    steps: [
      "Maintain benefit plans and confirm employee/employer cost treatment.",
      "Enroll employees in the correct active plans and review effective dates.",
      "Use Documents for contracts, W-4/I-9 files, IDs, work authorization, licenses/certifications and acknowledgements.",
      "Review expiring documents and renew/replace them before expiration.",
      "Keep employee documents private and use the application access controls rather than public file links.",
    ],
  },
  {
    id: "hr-compliance",
    title: "Compliance & Emergency Contacts",
    category: "Personnel & HR",
    summary: "Maintain employment compliance indicators, withholding profile inputs and emergency contacts.",
    roles: [...admins, "hr"],
    durationMinutes: 9,
    path: "/personnel/compliance",
    steps: [
      "Confirm W-4 and I-9 status based on the employee's actual documentation.",
      "Track work authorization expiration where applicable.",
      "Maintain federal/state/local withholding profile inputs used by payroll processing.",
      "Store only the supported tax identifier information; the current design intentionally avoids plaintext full SSN storage.",
      "Maintain at least one accurate emergency contact and identify the primary contact.",
    ],
    warnings: ["Do not paste full SSNs or other highly sensitive identifiers into HR notes."],
  },
  {
    id: "hr-lifecycle-performance",
    title: "Onboarding, Offboarding & Performance",
    category: "Personnel & HR",
    summary: "Use structured lifecycle tasks and performance reviews instead of informal reminders.",
    roles: [...admins, "hr"],
    durationMinutes: 11,
    path: "/personnel/lifecycle",
    steps: [
      "Create/assign onboarding tasks for documentation, account access, equipment, benefits and orientation.",
      "Track due dates and completion rather than relying on chat/email memory.",
      "For offboarding, track final payroll, benefits termination, equipment return, account disablement and record archiving.",
      "Use Performance for probation, periodic, annual or ad-hoc reviews.",
      "Document goals, strengths, development areas and manager comments factually and professionally.",
    ],
  },
  {
    id: "hr-reports",
    title: "HR Reports & Daily Controls",
    category: "Reports & Controls",
    summary: "Use HR reporting to identify exceptions that need attention before they become payroll or compliance problems.",
    roles: [...admins, "hr"],
    durationMinutes: 7,
    path: "/personnel/reports",
    steps: [
      "Review headcount and employment status totals.",
      "Check attendance, overtime, absence/no-show and lateness exceptions.",
      "Review pending leave and PTO balances.",
      "Monitor expiring employee documents and open onboarding/offboarding tasks.",
      "Review payroll totals before and after each payroll cycle.",
    ],
  },
  {
    id: "admin-users-roles",
    title: "Users, Roles & Access",
    category: "Administration",
    summary: "Create user accounts and assign least-privilege roles without weakening operational controls.",
    roles: admins,
    durationMinutes: 10,
    path: "/users",
    steps: [
      "Create/invite a user with the minimum role needed for the job.",
      "Use Sales for customer/order workflows, Finance for financial workflows, HR for personnel, Warehouse for stock operations and Shipping for shipment execution.",
      "Review Roles & Access before expanding permissions.",
      "Deactivate accounts promptly when access is no longer required.",
      "After changing a role, have the user refresh or sign in again so permissions are refreshed.",
    ],
    warnings: ["Do not use Admin as a default role just to solve a missing permission."],
  },
  {
    id: "admin-settings",
    title: "Company & System Settings",
    category: "Administration",
    summary: "Maintain Oakwell Cabinetry company, localization, document, email and notification settings safely.",
    roles: admins,
    durationMinutes: 8,
    path: "/settings/general",
    steps: [
      "Use Company settings for company identity/contact information used by the application and documents.",
      "Use Localization for supported locale/date/time behavior.",
      "Use Documents for document-related configuration and branding.",
      "Use Email and Notifications to manage communication behavior.",
      "Use Email Delivery Log to troubleshoot delivery before changing configuration.",
    ],
  },
  {
    id: "reports-operational",
    title: "Operational Reports & Audit Mindset",
    category: "Reports & Controls",
    summary: "Use reports and movement history to investigate issues before making corrective changes.",
    roles: [...admins, "sales", "finance", "warehouse"],
    durationMinutes: 7,
    path: "/reports/inventory",
    steps: [
      "Use Inventory Reports for stock position analysis.",
      "Use Movement Reports/Stock Movements to trace how quantities changed.",
      "Compare reports with the underlying transaction/order/shipment context before correcting data.",
      "Prefer controlled correction workflows that preserve history instead of deleting evidence of an error.",
    ],
  },
];

export const TRAINING_CATEGORIES: TrainingCategory[] = [
  "Getting Started",
  "Sales & Customers",
  "Inventory & Warehouse",
  "Shipping & Installation",
  "Finance",
  "Personnel & HR",
  "Administration",
  "Reports & Controls",
];
