"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from "react";
import Button from "@/components/ui/button/Button";
import Input from "@/components/form/input/InputField";
import Select from "@/components/form/Select";
import { supabase } from "@/lib/supabase/client";

const methods = ["each", "sq_ft", "linear_ft", "flat"].map((value) => ({ value, label: value }));
const configs = [
  { key: "stone_type", title: "Stone Types", table: "countertop_stone_types", columns: "id,name,is_active", fields: ["name"] },
  { key: "material_band", title: "Material Price Bands", table: "countertop_material_price_bands", columns: "id,code,price_per_sqft,is_active", fields: ["code", "price_per_sqft"] },
  { key: "edge", title: "Edge Profiles", table: "countertop_edge_profiles", columns: "id,name,pricing_method,unit_price,is_active", fields: ["name", "pricing_method", "unit_price"] },
  { key: "service", title: "Services", table: "countertop_services", columns: "id,name,pricing_method,unit_price,is_active", fields: ["name", "pricing_method", "unit_price"] },
];

export default function CountertopReferenceManager() {
  const [rows, setRows] = useState<Record<string, any[]>>({}); const [drafts, setDrafts] = useState<Record<string, any>>({}); const [editing, setEditing] = useState<Record<string, string | null>>({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); const entries = await Promise.all(configs.map(async (c) => [c.key, (await supabase.from(c.table).select(c.columns).order(c.key === "material_band" ? "sort_order" : "name"))] as const)); const failed = entries.find(([, result]) => result.error); if (failed) setError("Unable to load countertop references."); setRows(Object.fromEntries(entries.map(([key, result]) => [key, result.data ?? []]))); setLoading(false); }
  useEffect(() => { void load(); }, []);
  function setField(key: string, field: string, value: string) { setDrafts((d) => ({ ...d, [key]: { ...d[key], [field]: value } })); }
  async function save(config: typeof configs[number]) { const draft = drafts[config.key] ?? {}; setSaving(config.key); setError(null); setMessage(null); const { error: e } = await supabase.rpc("upsert_countertop_reference", { p_kind: config.key, p_id: editing[config.key] || null, p_name: draft.name || null, p_code: draft.code || null, p_price: draft.price_per_sqft || draft.unit_price || null, p_pricing_method: draft.pricing_method || null, p_is_active: draft.is_active !== false }); setSaving(null); if (e) { setError(e.message.includes("already exists") ? "Duplicate reference." : e.message); return; } setMessage(`${config.title} saved.`); setDrafts((d) => ({ ...d, [config.key]: {} })); setEditing((x) => ({ ...x, [config.key]: null })); await load(); }
  async function toggle(config: typeof configs[number], row: any) { setSaving(config.key); const { error: e } = await supabase.rpc("upsert_countertop_reference", { p_kind: config.key, p_id: row.id, p_name: row.name, p_code: row.code, p_price: row.price_per_sqft ?? row.unit_price, p_pricing_method: row.pricing_method, p_is_active: !row.is_active }); setSaving(null); if (e) setError(e.message); else await load(); }
  if (loading) return <section className="rounded-2xl border p-5">Loading countertop reference management…</section>;
  return <section className="space-y-6">{error && <p className="text-sm text-error-600">{error}</p>}{message && <p className="text-sm text-success-600">{message}</p>}{configs.map((config) => { const draft = drafts[config.key] ?? {}; return <section key={config.key} className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><h2 className="text-lg font-semibold">{config.title}</h2><div className="mt-4 grid gap-3 md:grid-cols-4">{config.fields.map((field) => field === "pricing_method" ? <Select key={field} options={methods} defaultValue={draft[field] ?? ""} onChange={(v) => setField(config.key, field, v)} /> : <Input key={field} placeholder={field} value={draft[field] ?? ""} onChange={(e) => setField(config.key, field, e.target.value)} />)}<Button disabled={saving === config.key} onClick={() => save(config)}>{saving === config.key ? "Saving…" : editing[config.key] ? "Save changes" : "Add"}</Button></div>{(rows[config.key] ?? []).length === 0 ? <p className="mt-4 text-sm text-gray-500">No references.</p> : <div className="mt-4 space-y-2">{(rows[config.key] ?? []).map((row) => <div key={row.id} className="flex flex-wrap items-center gap-3 border-b py-2 text-sm"><span className="min-w-36">{row.name ?? row.code}</span><span>{row.price_per_sqft ?? row.unit_price ?? ""}</span><span>{row.pricing_method ?? ""}</span><span>{row.is_active ? "Active" : "Inactive"}</span><Button variant="outline" size="sm" onClick={() => { setEditing((x) => ({ ...x, [config.key]: row.id })); setDrafts((d) => ({ ...d, [config.key]: { ...row, price_per_sqft: row.price_per_sqft, unit_price: row.unit_price } })); }}>Edit</Button><Button variant="outline" size="sm" disabled={saving === config.key} onClick={() => toggle(config, row)}>{row.is_active ? "Deactivate" : "Activate"}</Button></div>)}</div>}</section>; })}</section>;
}
