"use client";
import { FormEvent, useEffect, useState } from "react";

type State="loading"|"ready"|"submitting"|"success"|"error";
type VerifyResponse={access_token?:string;user?:{app_metadata?:Record<string,unknown>}};
function config(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;return url&&key?{url,key}:null;}
async function messageFrom(response:Response,fallback:string){try{const body=await response.json() as {message?:string;msg?:string;error_description?:string};return body.message||body.msg||body.error_description||fallback;}catch{return fallback;}}

export default function AccountActivationForm(){
 const [state,setState]=useState<State>("loading");const [tokenHash,setTokenHash]=useState("");const [password,setPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [message,setMessage]=useState("");
 useEffect(()=>{const c=config();const params=new URLSearchParams(window.location.hash.replace(/^#/,""));const token=params.get("token_hash")||"";const type=params.get("type")||"";window.history.replaceState({},"",window.location.pathname);if(!c){setMessage("Account activation is not configured.");setState("error");return;}if(!token||type!=="recovery"){setMessage("Open the activation link from your invitation email.");setState("error");return;}setTokenHash(token);setState("ready");},[]);
 async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();const c=config();if(!c||!tokenHash){setMessage("This invitation can no longer be used. Ask your Oakwell administrator to resend it.");setState("error");return;}if(password.length<8){setMessage("Use a password with at least 8 characters.");return;}if(password!==confirmPassword){setMessage("Passwords do not match.");return;}setMessage("");setState("submitting");let accessToken="";
  try{const verify=await fetch(`${c.url}/auth/v1/verify`,{method:"POST",headers:{apikey:c.key,"Content-Type":"application/json"},body:JSON.stringify({token_hash:tokenHash,type:"recovery"}),cache:"no-store"});if(!verify.ok)throw new Error(await messageFrom(verify,"The invitation is invalid or expired."));const verified=await verify.json() as VerifyResponse;accessToken=verified.access_token||"";const accountType=verified.user?.app_metadata?.account_type;if(!accessToken||(accountType!=="dealer_portal"&&accountType!=="customer_portal"))throw new Error("This invitation cannot be used here.");const headers={apikey:c.key,Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"};const passwordResponse=await fetch(`${c.url}/auth/v1/user`,{method:"PUT",headers,body:JSON.stringify({password})});if(!passwordResponse.ok)throw new Error(await messageFrom(passwordResponse,"Unable to set the password."));const activationResponse=await fetch(`${c.url}/rest/v1/rpc/activate_store_portal_user`,{method:"POST",headers,body:"{}",cache:"no-store"});if(!activationResponse.ok)throw new Error(await messageFrom(activationResponse,"Unable to activate the account."));const activation=await activationResponse.json() as {ok?:boolean};if(!activation.ok)throw new Error("This invitation can no longer be activated.");await fetch(`${c.url}/auth/v1/logout`,{method:"POST",headers}).catch(()=>undefined);setTokenHash("");setPassword("");setConfirmPassword("");setMessage("Your account is activated. You can now sign in.");setState("success");}catch(error){if(accessToken&&c)await fetch(`${c.url}/auth/v1/logout`,{method:"POST",headers:{apikey:c.key,Authorization:`Bearer ${accessToken}`}}).catch(()=>undefined);setTokenHash("");setMessage(error instanceof Error?error.message:"Unable to activate the account.");setState("error");}}
 if(state==="loading")return <p className="text-secondary mb-0">Checking invitation…</p>;if(state==="success")return <div className="alert alert-success mb-0" role="status">{message}</div>;
 return <form onSubmit={handleSubmit}>{message?<div className="alert alert-warning" role="alert">{message}</div>:null}<div className="mb-3"><label className="form-label" htmlFor="account-new-password">Password</label><input id="account-new-password" className="form-control" type="password" autoComplete="new-password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} disabled={state!=="ready"} required/></div><div className="mb-4"><label className="form-label" htmlFor="account-new-password-confirm">Confirm password</label><input id="account-new-password-confirm" className="form-control" type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} disabled={state!=="ready"} required/></div><button className="btn btn-dark w-100" type="submit" disabled={state!=="ready"}>{state==="submitting"?"Activating…":"Activate account"}</button></form>;
}
